# Generated by Django 3.2.18 on 2023-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLiveOIChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
                ('max_ceoi_strike', models.IntegerField(default=0)),
                ('put_max_ceoi_strike', models.IntegerField(default=0)),
                ('call_percentage', models.IntegerField(default=0)),
                ('put_percentage', models.IntegerField(default=0)),
                ('call_ceoi_total', models.IntegerField(default=0)),
                ('put_ceoi_total', models.IntegerField(default=0)),
                ('put_final', models.IntegerField(default=0)),
                ('call_final', models.IntegerField(default=0)),
                ('max_call_volume', models.IntegerField(default=0)),
                ('max_put_volume', models.IntegerField(default=0)),
                ('max_call_volume_strike', models.IntegerField(default=0)),
                ('max_put_volume_strike', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FirstLiveOIPercentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
                ('strikegap', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FirstLiveOITotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
                ('strikegap', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FirstVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('max_call_volume', models.IntegerField(default=0)),
                ('max_put_volume', models.IntegerField(default=0)),
                ('max_call_volume_strike', models.IntegerField(default=0)),
                ('max_put_volume_strike', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('max_call_volume', models.IntegerField(default=0)),
                ('max_put_volume', models.IntegerField(default=0)),
                ('max_call_volume_strike', models.IntegerField(default=0)),
                ('max_put_volume_strike', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LiveHighLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('high', models.CharField(default='', max_length=20)),
                ('low', models.CharField(default='', max_length=20)),
                ('ltp', models.CharField(max_length=20)),
                ('cross', models.CharField(default='None', max_length=20)),
                ('high_low_diff', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LiveVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('max_call_volume', models.IntegerField(default=0)),
                ('max_put_volume', models.IntegerField(default=0)),
                ('max_call_volume_strike', models.IntegerField(default=0)),
                ('max_put_volume_strike', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Totalruntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_run', models.FloatField(default=0)),
                ('total_symbols', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='historyoichange',
            name='max_call_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historyoichange',
            name='max_call_volume_strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historyoichange',
            name='max_put_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historyoichange',
            name='max_put_volume_strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='max_call_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='max_call_volume_strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='max_put_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='max_put_volume_strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='liveequityresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
